### ISSUE TITLE
Make coin drops independent of message sending

### ISSUE THREAD

**Issue by ivandardi** [BlobEmoji/coindrop#2]
People are spamming the chat just so the coin drops. That happens because the coin drop is determined on the `on_message` event.

My suggested proposal is that the coin dropping happen in a background task so that it doesn't depend on messages. Then it would look something like

```py
while True:
    drop_coin()
    time_to_sleep = calculate_sleep_time_using_exponential_stuff()
    await asyncio.sleep(time_to_sleep)
```

**Comment by scarletcafe** [comment]
This would allow people in lesser active timezones to have an advantage as there would be less people to compete with in grabbing coins, but still relatively equal frequency. It would also require background task cleanup when the cog reloads.

Rather than this, my plan is to introduce 'slow mode' chat calming that reduces drop chance significantly on suspicious activity spikes.
