### ISSUE TITLE
Make it so .commands that happen outside of #bot-commands don't trigger

### ISSUE THREAD

**Issue by ivandardi** [BlobEmoji/coindrop#3]
People are running commands on #general and psyching people into spamming `.pick` because that makes the BlobCoin bot send a message.

My suggested proposal is that a check is added to all commands (other than .pick) that checks if the command is happening in the #bot-commands channel. If it is, then it will execute the command. If not, it will delete the message that triggered the command and possibly warn the user via DM or chat message that bot commands should be run in #bot-commands.

**Comment by scarletcafe** [comment]
I don't like this implementation because there are instances in which users would want to display either their own coins, or the stats page, in general without it flooding the chat. However, I do plan to curb usage of the bot's commands in general via channel-specific cooldowns. Until then, I'll keep this issue open.
